- name: install archive handlers
  apt:
    name: "{{ item }}"
  with_items:
  - unzip
  - tar

- name: Check if Nomad is already installed
  stat:
    path: "{{ nomad_install_dir }}/nomad"
  register: nomad_bin
  changed_when: false

- name: Download Nomad
  become: yes
  get_url:
    url: "{{ nomad_url }}"
    dest: "{{ nomad_download_dir }}/nomad.zip"
    sha256sum: "{{ nomad_sha256sum }}"

- name: Unzip Nomad to installation directory
  become: yes
  unarchive:
    src: "{{ nomad_download_dir }}/nomad.zip"
    dest: "{{ nomad_install_dir }}"
    creates: "{{ nomad_install_dir }}/nomad"
    remote_src: True

- name: Create Nomad configuration directory
  become: yes
  file:
    path: "{{ nomad_config_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create Nomad data directory
  become: yes
  file:
    path: "{{ nomad_data_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
    state: directory

- name: Create Nomad systemd configuration
  become: yes
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: Create Nomad configuration file
  become: yes
  template:
    src: nomad.hcl.j2
    dest: "{{ nomad_config_dir }}/nomad.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad
