- name: Create Nomad group
  become: yes
  group:
    name: "{{ nomad_group }}"
    system: yes
    state: present
- name: Create Nomad user
  become: yes
  user:
    name: "{{ nomad_user }}"
    shell: /bin/false
    createhome: no
    group: "{{ nomad_group }}"
    system: yes
    state: present
- name: Create Nomad server configuration file
  become: yes
  template:
    src: server.hcl.j2
    dest: "{{ nomad_config_dir }}/server.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad
- name: Create Nomad tls config
  become: yes
  template:
    src: tls.hcl.j2
    dest: "{{ nomad_config_dir }}/tls.hcl"
    owner: root
    group: root
    mode: 0644
  when: nomad_tls_enable == True
  notify:
    - restart nomad
